// <auto-generated />
using System;
using KokaarWebApi.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KokaarWebApi.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200424024241_AddRowVersion")]
    partial class AddRowVersion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KokaarWebApi.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Berry",
                            Country = "Mali",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1650, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "armand@gmail.com",
                            Name = "Griffin Beak Eldritch",
                            PhoneNumber = "+15149969897"
                        },
                        new
                        {
                            Id = 2,
                            City = "Nancy",
                            Country = "Cameroun",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1668, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "armand@gmail.com",
                            Name = "Swashbuckler Rye",
                            PhoneNumber = "+15149969897"
                        },
                        new
                        {
                            Id = 3,
                            City = "Eli",
                            Country = "Canada",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1701, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "armand@gmail.com",
                            Name = "Ivory Bones Sweet",
                            PhoneNumber = "+15149969897"
                        },
                        new
                        {
                            Id = 4,
                            City = "Arnold",
                            Country = "Canada",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1702, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "armand@gmail.com",
                            Name = "The Unseen Stafford",
                            PhoneNumber = "+15149969897"
                        },
                        new
                        {
                            Id = 5,
                            City = "Seabury",
                            Country = "Maps",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1690, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "armand@gmail.com",
                            Name = "Toxic Reyson",
                            PhoneNumber = "+15149969897"
                        },
                        new
                        {
                            Id = 6,
                            City = "Rutherford",
                            Country = "France",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1723, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "armand@gmail.com",
                            Name = "Fearless Cloven",
                            PhoneNumber = "+15149969897"
                        },
                        new
                        {
                            Id = 7,
                            City = "Atherton",
                            Country = "Cameroun",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1721, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "armand@gmail.com",
                            Name = "Crow Ridley",
                            PhoneNumber = "+15149969897"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
